language: cpp

os: linux

compiler: g++-7

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - g++-7-multilib
    - cxxtest
    - lcov

script: 
  - mkdir build
  - mkdir log
  - make test
  - ./build/test.out --help-tests
  - ./build/test.out 
  - export CODECOV_TOKEN="d0a350aa-26ff-4385-b738-5c25e2a35a20"
  - lcov --no-external --capture --directory . --output-file cov.info
  - bash <(curl -s https://codecov.io/bash) -f cov.info

sudo: false
dist: trusty
