language: cpp

os: linux

compiler: g++-7

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - g++-7-multilib
    - cxxtest
    - lcov

script: 
  - mkdir build
  - mkdir log
  - make test
  - ./build/test.out --help-tests
  - ./build/test.out 
  - export CODECOV_TOKEN="c4ffb9a1-7224-4bb0-aaeb-65115bb4fbc7"
  - lcov --no-external --capture --directory . --output-file cov.info
  - bash <(curl -s https://codecov.io/bash) -f cov.info

sudo: false
dist: trusty
